parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wine_gallery_sf2
    database_user: root
    database_password: '1234'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 26b89a90c9d60b2b34976c09db8151975096df0e
    database_path: null