acme_simple_crm:
    resource: "@AcmeSimpleCrmBundle/Controller/"
    type:     annotation
    prefix:   /

acme_wine:
    resource: "@AcmeWineBundle/Controller/"
    type:     annotation
    prefix:   /

